spring:
  r2dbc:
    url: r2dbc:mysql://host.docker.internal:3306/tecnologiasdb
    username: root
    password: ""
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    web-application-type: reactive

server:
  port: 8085

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
  packages-to-scan: gabs.tecnologias.infraestructure.adapter.in