spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/tecnologiasdb
    username: root
    password: ""
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    web-application-type: reactive

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html