spring:
  r2dbc:
    url: r2dbc:mysql://host.docker.internal:3306/capacidadesdb
    username: root
    password: ""
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    web-application-type: reactive

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  packages-to-scan: gabs.capacidades.infraestructure.adapter.in
  paths-to-match: /api/**